- name: Install git
  hosts: remote1
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name:
    apt: name=git state=present update_cache=yes
